name: Combination API App DEPLOY

on:
  workflow_dispatch:

env:
  ## usage of repository env is a workaround cause env variables can not be passed in reusable workflows
  APP: ${{ vars.COMBINATION_API_APP }}

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  code-quality:
    name: Code standards
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_code_quality.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  test:
    name: Test application
    needs: code-quality
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_test.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  build:
    name: Build application
    needs: test
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_zip_archive.yml@864b36cd678156b3322dfa6cd19d7265af74e382
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  deploy-dev:
    name: Deploy application to DEV
    needs: build
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_deploy.yml@864b36cd678156b3322dfa6cd19d7265af74e382
    with:
      application: ${{ vars.COMBINATION_API_APP }}
      lambdas-common-vars: ${{ needs.build.outputs.lambdas-common-vars }}
      environment: dev
    secrets:
      aws-access-key-id: ${{ secrets.COMBINATION_API_APP_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.COMBINATION_API_APP_AWS_SECRET_ACCESS_KEY }}