name: Destroy Combination API app

on:
  push:
    branches:
      - "combination-api-app-destroy-job"
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy application DEV
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 install python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: "📦 install dependencies"
        run: cd combination-api-app/source && pip install -r requirements.txt

      - name: "🔍 run build"
        run: chmod +x .github/workflows/scripts/combination-api-app/build.sh && .github/workflows/scripts/combination-api-app/build.sh

      - name: "🔧 install terraform 1.3.8"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.8

      - name: "🔧 install terragrunt 0.43.2"
        run: chmod +x .github/workflows/scripts/combination-api-app/terragrunt_install.sh && .github/workflows/scripts/combination-api-app/terragrunt_install.sh

      - name: "🔍 run terragrunt stuff"
        run: cd combination-api-app/infrastructure/environments/dev && terragrunt init && terragrunt destroy -auto-approve

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.COMBINATION_API_APP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMBINATION_API_APP_AWS_SECRET_ACCESS_KEY }}
