name: Combination API App CLEAR

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  build:
    name: Build application
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_zip_archive.yml@beddaa1707806e9a5c9671f79453763629d0d5ac
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  clear:
    name: Clear application
    needs: build
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_clear.yml@b4eab12da4e513db687d117474c906419709edb5
    with:
      application: ${{ vars.COMBINATION_API_APP }}
      lambdas-common-vars: ${{ needs.build.outputs.lambdas-common-vars }}
      environment: ${{ inputs.environment }}
    secrets:
      aws-access-key-id: ${{ secrets.COMBINATION_API_APP_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.COMBINATION_API_APP_AWS_SECRET_ACCESS_KEY }}
