name: Combination API App CLEAR

on:
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  build:
    name: Build application
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_zip_archive.yml@beddaa1707806e9a5c9671f79453763629d0d5ac
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  destroy:
    name: Destroy application DEV
    needs: build
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.COMBINATION_API_APP_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.COMBINATION_API_APP_AWS_SECRET_ACCESS_KEY }}
      LAMBDA_ARTIFACT_NAME: ${{ needs.build-lambda-api-composer.outputs.lambda-artifact-name }}
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "💾 fetch lambda artifact"
        uses: actions/cache@v3
        with:
          key: ${{ vars.COMBINATION_API_APP }}-artifacts-${{ github.run_number }}
          path: ./${{ inputs.application }}/source/target
          fail-on-cache-miss: true

      - name: "🔧 install terraform 1.3.8"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.8

      - name: "🔧 install terragrunt 0.43.2"
        run: |
          curl -LJO https://github.com/gruntwork-io/terragrunt/releases/download/v0.43.2/terragrunt_linux_amd64
          mv terragrunt_linux_amd64 terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin
          ls -l /usr/local/bin
          terragrunt --version

      - name: "📦 prepare common_vars file for terragrunt"
        run: |
          (echo ""; echo "lambda_artifact_name: \"${LAMBDA_ARTIFACT_NAME}\"") >> ./${{ vars.COMBINATION_API_APP }}/infrastructure/environments/common_vars.yaml
          cat ./${{ vars.COMBINATION_API_APP }}/infrastructure/environments/common_vars.yaml

      - name: "🔍 run terragrunt stuff"
        run: cd combination-api-app/infrastructure/environments/dev && terragrunt init && terragrunt destroy -auto-approve
