name: Combination API App CLEAR

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@864b36cd678156b3322dfa6cd19d7265af74e382
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  build:
    name: Build application
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_zip_archive.yml@864b36cd678156b3322dfa6cd19d7265af74e382
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  clear:
    name: Clear application
    needs: build
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_clear.yml@864b36cd678156b3322dfa6cd19d7265af74e382
    with:
      application: ${{ vars.COMBINATION_API_APP }}
      lambdas-common-vars: ${{ needs.build.outputs.lambdas-common-vars }}
      environment: ${{ inputs.environment }}
    secrets:
      aws-access-key-id: ${{ secrets.COMBINATION_API_APP_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.COMBINATION_API_APP_AWS_SECRET_ACCESS_KEY }}
