name: Deploy Combination API app

on:
  workflow_dispatch:

jobs:
  lint:
    name: Code standards
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 install python 3.9"
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'

      - name: "🔧 install pylint"
        run: pip install pylint

      - name: "🔍 lint code"
        run: cd combination-api-app/source && find . -type f -name "*.py" | xargs pylint

  test:
    name: Test application
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 install python 3.9"
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'

      - name: "📦 install dependencies"
        run: cd combination-api-app/source && pip install -r requirements.txt

      - name: "🔍 run tests"
        run: cd combination-api-app/source && python3 -m unittest tests.test_api_composer
