name: Combination API App DEPLOY

on:
  workflow_dispatch:

env:
  ## usage of repository env is a workaround cause env variables can not be passed in reusable workflows
  APP: ${{ vars.COMBINATION_API_APP }}

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  code-quality:
    name: Code standards
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_code_quality.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  test:
    name: Test application
    needs: code-quality
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_test.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.COMBINATION_API_APP }}

  build-lambda-api-composer:
    name: Build lambda api composer
    needs: test
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_zip_archive.yml@python-reusable-deploy-workflow
    with:
      application: ${{ vars.COMBINATION_API_APP }}
      lambda-name: lambda-api-composer
      # TODO find a solution to bind lambda source directory to all required file in archive
      files-folders-to-add: "api_composer __init__.py"

  deploy-dev:
    name: Deploy application to DEV
    needs: build-lambda-api-composer
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_deploy.yml@python-reusable-deploy-workflow
    with:
      application: ${{ vars.COMBINATION_API_APP }}
      lambda-artifact-name: ${{ needs.build-lambda-api-composer.outputs.lambda-artifact-name }}
      environment: dev
    secrets:
      aws-access-key-id: ${{ secrets.COMBINATION_API_APP_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.COMBINATION_API_APP_AWS_SECRET_ACCESS_KEY }}