name: Reminder App DEPLOY

on:
  push:
    branches:
      - "reminder-app-initial-ci-cd"
  workflow_dispatch:

jobs:

  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@d5bbacdca00f5d0fb36ed855fd17646a9f2b8c78
    with:
      application: ${{ vars.REMINDER_APP }}
      source-dir: source/backend

  # TODO: code quality

  test:
    name: Test application
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_test.yml@d5bbacdca00f5d0fb36ed855fd17646a9f2b8c78
    with:
      application: ${{ vars.REMINDER_APP }}
      source-dir: source/backend

  build:
    name: Build application
    needs: test
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_docker_image.yml@aa67ca00bde47124a5d981e87966c900529e8fcb
    with:
      application: ${{ vars.REMINDER_APP }}
      source-dir: source/backend

  prepare-environment-variables:
    needs: build
    strategy:
      matrix:
        environment: [ dev ]
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    env:
      application: ${{ vars.REMINDER_APP }}
    steps:
      - name: "🔧 construct environment variables file"
        env:
          REMINDER_APP_AWS_ACCESS_KEY_ID: ${{ secrets.REMINDER_APP_AWS_ACCESS_KEY_ID }}
          REMINDER_APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.REMINDER_APP_AWS_SECRET_ACCESS_KEY }}
        run: |
          env_vars_file="./env_vars_${{ matrix.environment }}.txt"

          echo "aws_region_${{ matrix.environment }}=${{ vars.REMINDER_APP_AWS_REGION }}" >> $env_vars_file

          echo "aws_repository_uri_${{ matrix.environment }}=${{ vars.REMINDER_APP_AWS_REPOSITORY_URI }}" >> $env_vars_file


          echo "::add-mask::$REMINDER_APP_AWS_ACCESS_KEY_ID"
          echo "aws_access_key_id_${{ matrix.environment }}=$REMINDER_APP_AWS_ACCESS_KEY_ID" >> $env_vars_file

          echo "::add-mask::$REMINDER_APP_AWS_SECRET_ACCESS_KEY"
          echo "aws_secret_access_key_${{ matrix.environment }}=$REMINDER_APP_AWS_SECRET_ACCESS_KEY" >> $env_vars_file

      - name: "💾 save environment variables"
        uses: actions/cache@v3
        with:
          key: ${{ env.application }}-environment-variables-${{ github.run_number }}
          path: ./env_vars_${{ matrix.environment }}.txt

  deploy-dev:
    name: Deploy application to DEV
    needs: prepare-environment-variables
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_deploy_docker_image.yml@4bdbb895d64c04fc7274ae77cc4f9c035efa2b76
    with:
      environment: dev
      application: ${{ vars.REMINDER_APP }}
      source-dir: source/backend
