name: Reminder App DEPLOY

on:
  push:
    branches:
      - "reminder-app-initial-ci-cd"
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@d5bbacdca00f5d0fb36ed855fd17646a9f2b8c78
    with:
      application: ${{ vars.REMINDER_APP }}
      source-dir: source/backend

  # TODO: code quality

  test:
    name: Test application
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_test.yml@d5bbacdca00f5d0fb36ed855fd17646a9f2b8c78
    with:
      application: ${{ vars.REMINDER_APP }}
      source-dir: source/backend
