name: URL Shortener App DEPLOY

on:
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  code-quality:
    name: Code standards
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_code_quality.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  test:
    name: Test application
    needs: code-quality
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_test.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  pre-built:
    name: Prepare lambdas with dependant modules variable
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      lambdas-with-dependant-modules: ${{ steps.construct-variable.outputs.lambdas-with-dependant-modules }}
    steps:
      - name: "🔍 construct variable"
        id: construct-variable
        run: |
          LAMBDAS_WITH_DEPENDANT_MODULES=$(
          (
          cat <<-END
          lambda_create_short_url=lambda_create_short_url,dynamo_db,exception,__init__.py
          lambda_get_original_url=lambda_get_original_url,dynamo_db,exception,__init__.py
          END
          ) | tr '\n' ';'
          )

          echo "LAMBDAS_WITH_DEPENDANT_MODULES=${LAMBDAS_WITH_DEPENDANT_MODULES}"
          echo "lambdas-with-dependant-modules=${LAMBDAS_WITH_DEPENDANT_MODULES}" >> "$GITHUB_OUTPUT"

  build:
    name: Build application
    needs: pre-built
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_zip_archive.yml@1c71f0bcea456cecbedfc8b67cc540144217bb8d
    with:
      application: ${{ vars.URL_SHORTENER_APP }}
      lambdas-with-dependant-modules: ${{needs.pre-built.outputs.lambdas-with-dependant-modules}}

  deploy-dev:
    name: Deploy application to DEV
    needs: build
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_deploy.yml@1c71f0bcea456cecbedfc8b67cc540144217bb8d
    with:
      application: ${{ vars.URL_SHORTENER_APP }}
      lambdas-common-vars: ${{ needs.build.outputs.lambdas-common-vars }}
      environment: dev
    secrets:
      aws-access-key-id: ${{ secrets.URL_SHORTENER_APP_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.URL_SHORTENER_APP_AWS_SECRET_ACCESS_KEY }}
