name: URL Shortener App DEPLOY

on:
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_install_dependencies.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  code-quality:
    name: Code standards
    needs: install-dependencies
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_code_quality.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  test:
    name: Test application
    needs: code-quality
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_test.yml@b3892a9ea001951a4e89fd4ad2ab8c0e6b2d0b38
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  build:
    name: Build application
    needs: test
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_build_zip_archive.yml@beddaa1707806e9a5c9671f79453763629d0d5ac
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  deploy-dev:
    name: Deploy application to DEV
    needs: build
    uses: asventetsky/freecodecamp-aws-serverless-projects-common/.github/workflows/_python_deploy.yml@1c71f0bcea456cecbedfc8b67cc540144217bb8d
    with:
      application: ${{ vars.URL_SHORTENER_APP }}
      lambdas-common-vars: ${{ needs.build.outputs.lambdas-common-vars }}
      environment: dev
    secrets:
      aws-access-key-id: ${{ secrets.URL_SHORTENER_APP_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.URL_SHORTENER_APP_AWS_SECRET_ACCESS_KEY }}
