name: Deploy Url Shortener app

on:
  workflow_dispatch:

env:
  ## usage of repository env is a workaround cause env variables can not be passed in reusable workflows
  APP: ${{ vars.URL_SHORTENER_APP }}

jobs:
  install-dependencies:
    name: Install dependencies
    uses: ./.github/workflows/_python_install_dependencies.yml
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  code-quality:
    name: Code standards
    needs: install-dependencies
    uses: ./.github/workflows/_python_code_quality.yml
    with:
      application: ${{ vars.URL_SHORTENER_APP }}

  test:
    name: Test application
    needs: code-quality
    uses: ./.github/workflows/_python_test.yml
    with:
      application: ${{ vars.URL_SHORTENER_APP }}
