name: Deploy Url Shortener app

on:
  workflow_dispatch:

env:
  APP: url-shortener-app

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 install python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: "📦 install dependencies"
        run: |
          chmod +x .github/workflows/scripts/install_dependencies.sh && \
          .github/workflows/scripts/install_dependencies.sh "${{ env.APP }}/source"

      - name: "💾 save project dependencies"
        uses: actions/cache@v3
        with:
          key: ${{ env.APP }}-dependencies-${{ github.run_number }}
          path: ./${{ env.APP }}/source/venv

  lint:
    name: Code standards
    needs: install-dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 install python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: "💾 fetch project dependencies"
        uses: actions/cache@v3
        with:
          key: ${{ env.APP }}-dependencies-${{ github.run_number }}
          path: ./${{ env.APP }}/source/venv
          fail-on-cache-miss: true

      - name: "🔍 lint code"
        run: cd ${{ env.APP }}/source && source venv/bin/activate && find . -type f -name "*.py" -not -path "./venv/*" | xargs pylint

  test:
    name: Test application
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 install python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: "💾 fetch project dependencies"
        uses: actions/cache@v3
        with:
          key: ${{ env.APP }}-dependencies-${{ github.run_number }}
          path: ./${{ env.APP }}/source/venv
          fail-on-cache-miss: true

      - name: "🔍 run tests"
        run: cd ${{ env.APP }}/source && source venv/bin/activate && python3 -m unittest discover test
